version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 45628:5432
    networks:
      - backend
    volumes:
      - database:/var/lib/postgres
      #- ./app/init/old:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
      - db_password

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: uvicorn backend.api.app:app --reload --host 0.0.0.0 --port 5000 #python3 -m app.api
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./backend:/usr/backend
    ports:
      - 5000:5000
    networks:
      - backend
    environment:
      DB_HOST: db
      DB_PORT: 8547
      DB_USER: root
      DB_PASSWORD: /run/secrets/db_password
      DB_DB: database
      VERSION: 1
    secrets:
      - db_password
    depends_on:
      - db

networks:
  backend:
    name: backend_network
volumes:
  database:
    # driver: local
    # driver_opts:
    #   type: "none"
    #   o: "bind"
    #   device: "./userdata"
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
